---

name: Setup - Install uv, python, and dependencies
description: This action contains some setup steps that are common to several workflows
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
    - name: Install Python dependencies
      run: uv sync --all-extras --dev
      shell: bash
