---

name: Tests on Push


on:
  push:
    branches-ignore:
      - main


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install poetry, python, and dependencies
        uses: ./.github/actions/setup
      - name: Linting with ruff
        run: poetry run ruff check . --output-format=github
      - name: Check formatting with ruff
        run: poetry run ruff format --check .
      - name: Linting with mypy
        run: poetry run mypy .

  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dsp-tools repo
        uses: actions/checkout@v4
      - name: Install poetry, python, and dependencies
        uses: ./.github/actions/setup
      - name: unittests
        run: poetry run pytest tests/unittests/
