---

name: Tests on Push


on:
  push:
    branches-ignore:
      - main


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install uv, python, and dependencies
        uses: ./.github/actions/setup
      - name: Linting with ruff
        run: uv run ruff check . --output-format=github
      - name: Check formatting with ruff
        run: uv run ruff format --check .
      - name: Linting with mypy
        run: uv run mypy .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install uv, python, and dependencies
        uses: ./.github/actions/setup
      - name: unittests
        run: uv run pytest tests/
